### ISSUE TITLE
Compatibility issue with Laminas 2.x

### ISSUE THREAD

**Issue by rsisco** [hawksearch/connector-magento-2#1]
Prerequisites:
* Magento 2.4.x
* `laminas/laminas-diactoros` 2.x
* `hawksearch/connector` (lastest `master` branch)

Steps to reproduce:
1. Access any page on the Magento site

Expected result:
* The page will load successfully

Actual result:
* The following error is displayed:
```
<!-- Hawk Search Header Includes -->
<link  rel="stylesheet"
       type="text/css"
       media="all"
       href="Error: Call to undefined method Laminas\Diactoros\UriFactory::create() in /Users/rsisco/Sites/cary/vendor/hawksearch/connector/Helper/Url.php:124
```

**Comment by rsisco** [comment]
The issue is because the `UriFactory.php` class has been updated in the 2.x branch of `laminas/laminas-diactoros`.

**Comment by martin-cod** [comment]
It is not relevant because `Laminas\Diactoros\UriFactory` was replaced by `GuzzleHttp\Psr7\UriFactory`
