### ISSUE TITLE
Unable to Update to 2.6.1 with Composer

### ISSUE THREAD

**Issue by bap14** [hawksearch/connector-magento-2#11]
You have tagged this as version 2.6.1; however, you neglected or forgot to update the composer.json property value itself to 2.6.1. This means packagist.org may not see the latest version as `2.6.1` or may be disseminating `2.6.1` as version `2.6.0`.

The real solution is to create a GitHub workflow to automatically update the composer.json "version" key when a new tag is created. This way the tagged release will have a fixed version matching the tag version.

![image](https://user-images.githubusercontent.com/15036826/232793391-a5bfd234-66ad-452b-bf1a-72806f8e94a9.png)
![image](https://user-images.githubusercontent.com/15036826/232793460-d6da357e-ac05-48bf-9db6-c3588d0f404e.png)

**Comment by martin-cod** [comment]
It was fixed in the repo
